- .gitignore
- .idea/copyright/SPDX_ALv2.xml
- .idea/copyright/profiles_settings.xml
- build.gradle
- src/main/java/org/opensearch/search/asynchronous/settings/LegacyOpendistroAsynchronousSearchSettings.java
- src/test/java/org/opensearch/search/asynchronous/settings/AsynchronousSearchSettingsTests.java
- src/test/java/org/opensearch/search/asynchronous/utils/QuadConsumer.java
1. Added the SPDX license header to the files with missing license headers.
2. Re-enabled the 'licenseHeaders' check in the build.gradle file.
3. Added an IntelliJ copyright profile to auto-generate the SPDX license header.
4. Updated the .gitignore file.
Related to - https://github.com/opensearch-project/opensearch-plugins/issues/49
Signed-off-by: Ketan Verma <ketan9495@gmail.com>
> Enabled automated license header checks

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- build.gradle
Bump to version 1.0.0.0 by removing the rc1 version qualifier from the plugin & necessary dependencies.
> bump version from rc1 to 1.0.0.0

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- build.gradle
This change adds a build properties to enable creating snapshot artifacts. This makes sure the OpenSearch and common-utils dependencies have the correct versions.
Also update the GHA workflows accordingly to build and test snapshots.
#30 
Signed-off-by: Rabi Panda <adnapibar@gmail.com>
> Add support for creating snapshot build artifacts.

- build.gradle
Signed-off-by: dblock <dblock@amazon.com>
This currently works in CI because we default to 1.1.0-SNAPSHOT anyway, but will break in the future and will be hard to debug. Thanks @mch2 for spotting this.
> Fix: typo in flag name.

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
[Describe what this change achieves]
> Updating CI workflows

- build.gradle
- checkstyle/checkstyle.xml
Signed-off-by: Surya Nistala <snistala@amazon.com>
Adds checkstyle plugin dependency. Removes suppression filter and comments out the deprecated snippet length check
Related to https://github.com/opensearch-project/OpenSearch/issues/1362
> Adds checkstyle plugin dependency.

- .github/CODEOWNERS
Signed-off-by: Ryan Bogan <rbogan@amazon.com>
Add codeowners support to repo
Progress on
[Meta issue](https://github.com/opensearch-project/project-meta/issues/31)
> Add codeowners support to repo

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>
CI workflows are not being run in release branches. 
Updating them to run on all of them pro-actively, since GHA is cheap.
> Updating CI workflows to run on all branches

- .github/workflows/build.yml
- README.md
- build.gradle
Signed-off-by: dblock <dblock@dblock.org>
Added CI for JDK 8, 11 and 14.
Closes https://github.com/opensearch-project/asynchronous-search/issues/66.
> Build on JDK 8, 11, 14

- .github/workflows/build.yml
- README.md
- build.gradle
Signed-off-by: dblock <dblock@dblock.org>
https://github.com/opensearch-project/asynchronous-search/pull/104 for 1.3.
Closes https://github.com/opensearch-project/asynchronous-search/issues/66.
> Build on JDK 8, 11, and 14.

- .github/workflows/build.yml
- build.gradle
> Remove support for JDK 8

- README.md
- build.gradle
- release-notes/opensearch-asynchronous-search.release-notes-1.3.0.0.md
Adding support for integration tests with remote cluster. Tested the changes with OS 1.2.4 setup locally.
https://github.com/opensearch-project/asynchronous-search/issues/63
> Adding support for integration tests with remote cluster

- build.gradle
Signed-off-by: Surya Sashank Nistala <snistala@amazon.com>
Adds support for -Dbuild.version_qualifier
#103
> Adds support for -Dbuild.version_qualifier

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- build.gradle
- src/main/java/org/opensearch/search/asynchronous/service/AsynchronousSearchPersistenceService.java
- src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchQueryIT.java
- src/test/java/org/opensearch/search/asynchronous/listener/AsynchronousSearchPartialResponseIT.java
- src/test/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementServiceIT.java
- src/test/java/org/opensearch/search/asynchronous/request/AsynchronousSearchRequestRoutingIT.java
Remove usage of mapping types
Piggybacking on @peterzhuamazon's #118 for the latest version of OS as 2.0.0-SNAPSHOT wasn't breaking build and issue was not reproducible.
#98 
> Remove usage of mapping types

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- build.gradle
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 1.3.1
Part of https://github.com/opensearch-project/opensearch-build/issues/1805
> Bump version to 1.3.1

- .github/workflows/build.yml
- build.gradle
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Make sure qualifier is default to alpha1
#103
> Make sure qualifier is default to alpha1

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- .github/workflows/release-workflow.yml
- DEVELOPER_GUIDE.md
Dropping support for JDK 14
https://github.com/opensearch-project/asynchronous-search/issues/121
> Remove JDK 14

- build.gradle
Remove rc1 build qualifier for GA release
> Remove rc1 build qualifier

- build.gradle
- scripts/build.sh
Signed-off-by: Surya Sashank Nistala <snistala@amazon.com>
Use custom plugin to publish zips to maven
#140
> Uses custom plugin to publish zips to maven

- src/main/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementService.java
- src/test/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementServiceTests.java
- src/test/java/org/opensearch/search/asynchronous/utils/TestUtils.java
> [Backport 2.x] Changed master nomenclature to cluster_manager

- README.md
Signed-off-by: cwillum <cwmmoore@amazon.com>
Added a "Getting Help" section that includes a link to the main OpenSearch product page, a link that goes direction to Asynchronous search in documentation, and a link to the OpenSearch Forum page.
This more closely corresponds to the information  found in the README.md file in all of the other plugins bundled with OpenSearch.
This fixes the issue for the Asynchronous search plugin in [#921](https://github.com/opensearch-project/documentation-website/issues/921).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/ma …
> Add Forum link in Asynchronous Search plugin README.md

- README.md
- build.gradle
- release-notes/opensearch-asynchronous-search.release-notes-2.4.0.0.md
> Merge release notes for 2.4 into 2.x

- src/test/java/org/opensearch/search/asynchronous/restIT/AsynchronousSearchRestIT.java
The window build is failing with the given below exception:
```
Suite: Test class org.opensearch.search.asynchronous.restIT.AsynchronousSearchRestIT
2> Jan 18, 2023 7:36:20 AM org.opensearch.client.RestClient logResponse
2> WARNING: request [POST https://localhost:9200/_opendistro/_asynchronous_search?keep_on_completion=true] returned 1 warnings: [299 OpenSearch-2.5.0-b8a8b6c4d7fc7a7e32eb2cb68ecad8057a4636ad "[POST /_opendistro/_asynchronous_search] is deprecated! Use [POST /_plugins/_asynchronous_search] instead."]
2> REPRODUCE WITH: gradlew ':integTest' --tests "org.opensearch.search.asynchronous.restIT.AsynchronousSearchRestIT.testGetWithKeepAliveUpdate" -Dtests.seed=AA4C903AE61D33F9 -Dtests.security.manager=false -Dtests.locale=en-PH -Dtests.timezone=Asia/Vladivostok -Druntime.java=17 …
```
> Integ test fix for testGetWithKeepAliveUpdate

- .github/workflows/maven-publish.yml
- build.gradle
> Publish snapshot to maven

- .github/CODEOWNERS
- MAINTAINERS.md
Updating the CODEOWNERS file to reflect the maintainers on MAINTAINERS.md file
Closes: #235 
> Updating the codeowners file

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- build.gradle
Increment version to 1.3.10 and update checksytle version to 8.29 for addressing  CVE-2019-10782
> Increment version to 1.3.10 and update checksytle version

- release-notes/opensearch-asynchronous-search.release-notes-2.8.0.0.md
- src/main/java/org/opensearch/search/asynchronous/request/SubmitAsynchronousSearchRequest.java
- src/main/java/org/opensearch/search/asynchronous/response/AsynchronousSearchResponse.java
- src/main/java/org/opensearch/search/asynchronous/rest/RestAsynchronousSearchStatsAction.java
- src/main/java/org/opensearch/search/asynchronous/task/AsynchronousSearchTask.java
- src/test/java/org/opensearch/search/asynchronous/restIT/AsynchronousSearchRestTestCase.java
- src/test/java/org/opensearch/search/asynchronous/utils/RestTestUtils.java
Fixing compilation issues in main due to packages changes in opensearch branch
> Fix compilation issues in main

- release-notes/opensearch-asynchronous-search.release-notes-2.9.0.0.md
- src/main/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceContext.java
- src/main/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceModel.java
- src/main/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementService.java
- src/main/java/org/opensearch/search/asynchronous/request/SubmitAsynchronousSearchRequest.java
- src/main/java/org/opensearch/search/asynchronous/rest/RestAsynchronousSearchStatsAction.java
- src/main/java/org/opensearch/search/asynchronous/task/AsynchronousSearchTask.java
- src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchStatsIT.java
- src/test/java/org/opensearch/search/asynchronous/restIT/AsynchronousSearchRestTestCase.java
- src/test/java/org/opensearch/search/asynchronous/utils/RestTestUtils.java
Add 2.9 release notes and fixing compilation errors.
https://github.com/opensearch-project/asynchronous-search/issues/299
> Add 2.9 release notes and fixing compilation errors

- .github/workflows/auto-release.yml
Adds a release workflow for the asynchronous search plugin similar to opensearch
https://github.com/opensearch-project/asynchronous-search/issues/234
> Adding release workflow for the asynchronous search

- .github/CODEOWNERS
- MAINTAINERS.md
Add mch2 anddross poojita-raj kotwanikunal and rishikesh1159 as maintainers
Add mch2 anddross poojita-raj kotwanikunal and rishikesh1159 as maintainers and codeowners.
N/A
> Updates to maintainers and codeowners

- MAINTAINERS.md
Maintainer's github ID was mixed up. 
Rishikesh's ID was set to Bukhtawar. Just fixed that typo. 
> Fixed Github ID for maintainer

- build.gradle
Fix broken bwcTests on main, this will require a manual backport to 2.x for version correctness.
This change also removes the requirement to commit plugin zips to the repo and downloads them on demand.
N/A 
> Fix bwcTests to point to correct 2.x version.

- src/main/java/org/opensearch/search/asynchronous/listener/AsynchronousSearchProgressListener.java
The `totalShards` in `SearchResponse` includes skipped shards, but the partial search response in `AsynchronousSearchProgressListener` does not account for this.
> Fix number of total shards in partial search response

- .gitignore
- build.gradle
- **Add .vscode to .gitignore.**
- **Bump bwc version -> 2.15.0.0.**
Increment version of opensearch + async search plugin packages 2.14 -> 2.15.
BWC test suite fails on main running 2.14 against the 3.0.0 SNAPSHOT.
`./gradlew bwcTestSuite`
N/A
> Bump bwc version -> 2.15

- src/test/java/org/opensearch/search/asynchronous/utils/TestUtils.java
ClusterService constructor deprecated by clusterManagerMetrics change.
https://github.com/opensearch-project/OpenSearch/commit/a254aa99e2221561c4de79a75d0de237eb759851#diff-944637c34088815d36760e219a0b4976bf492cdff44ef450b52ede0a13b0d9f0R104
> Update deprecated ClusterService constructor

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- build.gradle
> Set JDK21 as the baseline for the 3.0 major version

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
setup-java action failing with:
```
/usr/bin/docker exec  c1465ab46106f1d175e52fb4802c1fc82e264ec53dce8115e79c74a171cf3534 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
Fix per: https://github.com/opensearch-project/job-scheduler/pull/650/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION true in multi-node workflow

- build.gradle
Bump bwc version to 2.16 for release.
> Bump bwc test version -> 2.17

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- .github/workflows/release-workflow.yml
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Resolves #[Issue number to be closed when this PR is merged]
> Bump download and upload-artifact to v3

- build.gradle
Full restart bwc only restarts single node.
N/A
> Fix restart bwc

- release-notes/opensearch-asynchronous-search.release-notes-2.13.0.0.md
House keeping. 2.x is missing release notes.
`git checkout 2.13 -- release-notes/opensearch-asynchronous-search.release-notes-2.13.0.0.md
`
N/A
> Add missing release notes

- src/main/java/org/opensearch/search/asynchronous/request/SubmitAsynchronousSearchRequest.java
- src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchStatsIT.java
testStatsAcrossNodes is flaky and I suspect this is because we do not wait on the result of `AsynchronousSearchStatsRequest` before asserting that node stats equal their expected values. Integration tests fail with [this](https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/8632/pipeline/132#step-961-log-563) error and while a stack trace is not available it's suspiciously similar to the failure we see when we artificially ensure `statsResponse` is empty.
```
2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.search.asynchronous.integTests.AsynchronousSearchStatsIT.testStatsAcrossNodes" -Dtests.seed=53E00013C44B3A81 -Dtests.security.manager=false -Dtests.locale=en-BM -Dtests.timezone=Australia/Canberra -Druntime.java=21
2> …
```
> Wait on AsynchronousSearchStatsRequest before asserting on statsResponse

- .github/workflows/auto-release.yml
- .github/workflows/build.yml
- .github/workflows/maven-publish.yml
- .github/workflows/multi-node-test-workflow.yml
- .github/workflows/release-workflow.yml
Remove hard coded java versions - use java.matrix instead so we can easily add and remove java versions for each workflow. Build/publish/release with all supported versions - 11/17/21. Test only with java 21.
Standardize version of github actions:
actions/setup-java to v4
actions/checkout to v4
For containerized workflows the image published by opensearch-build does not have a high enough version of glibc to support these v4 actions. Here we downgrade to v3 which only needs node 16 and set `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true.
Should fix publish failure with java upgrade for that workflow: 11 -> 21.
For more information on following Developer Certificate of Origin …
> Standardize build/test github actions and java versions

- .github/CODEOWNERS
- MAINTAINERS.md
Adding Finn as maintainer after maintainer vote was held.
N/A
> Add Finn to maintainers and codeowners

- build.gradle
Nightlies failing due to opensearch_version being unnecessarily truncated.
https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/10311/pipeline/170/
```
1: Task failed with an exception.
-----------
* Where:
Build file '/tmp/tmph0d2bvyo/asynchronous-search/build.gradle' line: 283
* What went wrong:
A problem occurred evaluating root project 'asynchronous-search'.
> Invalid version format: '3.0'. Should be major.minor.revision[-(alpha|beta|rc)Number][-SNAPSHOT]
```
Likely reason 3.0.0 docker images are not being published.
Resolves #607
For more information on following Developer Certificate of Origin and …
> Remove version truncate to fix nightly build

- .github/workflows/maven-publish.yml
This step continues to fail due build.gradle `sourceCompatibility = JavaVersion.VERSION_21` requirement.
Limit publish workflow to java 21 only.
N/A
> Publish workflow to java 21 only

- build.gradle
Bump bwc version to 2.19 on main
This version bump is needed for backward compatibility testing on main since opensearch core has been version bumped to 2.19 and 3.0.0 nodes can only form a cluster with the last minor version (2.19 as of now) of the previous major version (2.x).
> Bump bwc version to 2.19 on main

- .github/dependabot.yml
Adds dependabot.yml to run on a weekly basis to monitor for outdated dependencies in this repo.
> Add dependabot.yml to monitor outdated dependencies

- .github/workflows/build.yml
Enable custom start commands and options to resolve GHA issues
Closes #666 https://github.com/opensearch-project/asynchronous-search/pull/673
https://github.com/opensearch-project/opensearch-build/issues/5178
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, …
> Enable custom start commands and options to resolve GHA issues

- .github/workflows/build.yml
* Enable custom start commands and options to resolve GHA issues
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
* Enable custom start commands and options to resolve GHA issues
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
* Enable custom start commands and options to resolve GHA issues
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
---------
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
(cherry picked from commit 8caf59ca49a3fa8c80cf05b1877b29bf32afd8b2)
Manual backport of #676
N/A
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/asynchronous-search/blob/main/CONTRIBUTIN …
> [Backport 2.x] Enable custom start commands and options to resolve GHA issues (#676)

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
Following up on #676 which fixes node versioning in the opensearch-build CI docker container.
- Apply the same change to multi-node-test-workflow
- Bump remaining v3 setup-java/checkout actions to v4
- Remove some orphaned comments
N/A
> Apply opensearch-build container fix to multi-node-test-workflow

- .github/workflows/auto-release.yml
- .github/workflows/build.yml
- .github/workflows/maven-publish.yml
- .github/workflows/multi-node-test-workflow.yml
- .github/workflows/release-workflow.yml
The following two changes are required to support bumping GHA versions to match main.
Currently CI/CD is failing on 2.19 due to deprecated GHAs (upload-artifact@v3).
Bump JDK version 11 -> 21
- https://github.com/opensearch-project/asynchronous-search/pull/582
Backport custom start command option for runner container
- https://github.com/opensearch-project/asynchronous-search/pull/676
- https://github.com/opensearch-project/asynchronous-search/pull/683
N/A
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/asynchronous-search/blob/main/CONTRIBUTING.md#developer-certificate-of …
> [Backport 2.19] Backport github action updates 

- build.gradle
`org.opensearch.plugin:transport-netty4-client` listed as compile time dependency in build.gradle but is not needed.
As far as I can tell this is an old artifact which is no longer used.
N/A
> Remove dependency on netty4 client

- build.gradle
Change qualifier from alpha1 to beta1
Resolves https://github.com/opensearch-project/asynchronous-search/issues/318#issuecomment-2758627582
> Change qualifier from alpha1 to beta1

- build.gradle
- release-notes/opensearch-asynchronous-search.release-notes-3.0.0.0.md
Add release notes for 3.0 GA.
Remove beta1 default version qualifier.
https://github.com/opensearch-project/asynchronous-search/issues/318
~~- [ ] New functionality includes testing.~~
~~- [ ] New functionality has been documented.~~
~~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
~~- [ ] Commits are signed per the DCO using `--signoff`.~~
~~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please …
> 3.0 Release notes

- .github/workflows/build.yml
- .github/workflows/multi-node-test-workflow.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Bump gradle to 8.14 and use jdk 24 in ci workflow
> Bump gradle to 8.14.3 and use jdk 24 in ci workflow
