opensearch-project/asynchronous-search

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/pull_request.md

Adds templates for PR, bug report and feature request

Adds templates for PR, bug report and feature request 

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
README.md
build.gradle
gradle.properties
src/main/java/com/amazon/opendistroforelasticsearch/search/asynchronous/processor/AsynchronousSearchPostProcessor.java
src/main/java/com/amazon/opendistroforelasticsearch/search/asynchronous/response/AsynchronousSearchResponse.java

Changes to use OpenSearch 1.0.0-alpha1 and some minor refactor

Changes to use OpenSearch 1.0.0-alpha1

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Build against 821c44c440 (1.0.0-alpha2)

build against 1.0.0-alpha2

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/search/asynchronous/plugin/AsynchronousSearchPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/search/asynchronous/rest/RestAsynchronousSearchStatsAction.java
src/main/java/com/amazon/opendistroforelasticsearch/search/asynchronous/rest/RestDeleteAsynchronousSearchAction.java
src/main/java/com/amazon/opendistroforelasticsearch/search/asynchronous/rest/RestGetAsynchronousSearchAction.java
src/main/java/com/amazon/opendistroforelasticsearch/search/asynchronous/rest/RestSubmitAsynchronousSearchAction.java
src/test/java/com/amazon/opendistroforelasticsearch/search/asynchronous/restIT/AsynchronousSearchRestIT.java
src/test/java/com/amazon/opendistroforelasticsearch/search/asynchronous/restIT/AsynchronousSearchRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/search/asynchronous/utils/RestTestUtils.java

Renames rest endoints with _opensearch path prefix

Rename opendistro rest apis

---

src/main/java/org/opensearch/search/asynchronous/context/active/AsynchronousSearchActiveStore.java
src/main/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementService.java
src/main/java/org/opensearch/search/asynchronous/plugin/AsynchronousSearchPlugin.java
src/main/java/org/opensearch/search/asynchronous/service/AsynchronousSearchService.java
src/main/java/org/opensearch/search/asynchronous/settings/LegacyOpendistroAsynchronousSearchSettings.java
src/test/java/org/opensearch/search/asynchronous/settings/AsynchronousSearchSettingsTests.java

Rename settings and add fallback for legacy opendistro settings
#11 

Rename settings 

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle
src/main/java/org/opensearch/search/asynchronous/context/AsynchronousSearchContext.java
src/main/java/org/opensearch/search/asynchronous/context/active/AsynchronousSearchActiveContext.java
src/main/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceContext.java
src/main/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceModel.java
src/main/java/org/opensearch/search/asynchronous/service/AsynchronousSearchPersistenceService.java
src/main/java/org/opensearch/search/asynchronous/service/AsynchronousSearchService.java
src/main/java/org/opensearch/search/asynchronous/transport/TransportAsynchronousSearchRoutingAction.java
src/main/java/org/opensearch/search/asynchronous/transport/TransportDeleteAsynchronousSearchAction.java
src/main/java/org/opensearch/search/asynchronous/transport/TransportGetAsynchronousSearchAction.java
src/main/java/org/opensearch/search/asynchronous/transport/TransportSubmitAsynchronousSearchAction.java
src/main/java/org/opensearch/search/asynchronous/utils/UserAuthUtils.java
src/test/java/org/opensearch/search/asynchronous/context/active/AsynchronousSearchActiveContextTests.java
src/test/java/org/opensearch/search/asynchronous/context/persistence/AsynchronousSearchPersistenceContextTests.java
src/test/java/org/opensearch/search/asynchronous/service/AsynchronousSearchServiceFreeContextTests.java
src/test/java/org/opensearch/search/asynchronous/service/AsynchronousSearchServiceTests.java
src/test/java/org/opensearch/search/asynchronous/service/AsynchronousSearchServiceUpdateContextTests.java
src/test/java/org/opensearch/search/asynchronous/service/persistence/AsynchronousSearchPersistenceServiceIT.java
src/test/java/org/opensearch/search/asynchronous/settings/AsynchronousSearchSettingsTests.java
src/test/java/org/opensearch/search/asynchronous/utils/TestClientUtils.java

Updates dependency version to 1.0.0.0-rc1
#11 

update dependency version to rc1

---

build-tools/pkgbuild.gradle
release-notes/opensearch-asynchronous-search.release-notes-1.0.0.0-rc1.md
src/main/java/org/opensearch/search/asynchronous/plugin/AsynchronousSearchPlugin.java

Adds release notes for 1.0.0.0-rc1
#11 

Release notes for 1.0.0.0-rc1

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml

Builds against 1.0 opensearch
#11 

Build against core 1.0 branch

---

release-notes/opensearch-asynchronous-search.release-notes-1.0.0.0.md

release notes for 1.0.0.0 ga version

---

integtest.sh

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Backports integtest.sh to 1.0 branch

Backports integtest script to 1.0 branch.

---

release-notes/opensearch-asynchronous-search.release-notes-1.1.0.0.md

Signed-off-by: Surya Nistala <snistala@amazon.com>
Adds release notes for 1.1.0.0 release

Adds release notes for 1.1.0.0 release

---

.github/workflows/dco-check.yml

Signed-off-by: Surya Nistala <snistala@amazon.com>
Adds DCO check
#47 

Adds DCO check

---

release-notes/opensearch-asynchronous-search.release-notes-1.2.0.0.md

Signed-off-by: Surya Nistala <snistala@amazon.com>
[Describe what this change achieves]

Surrounds 1.2 release notes PR details with parantheses

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Signed-off-by: Surya Sashank Nistala <snistala@amazon.com>
Upgrade plugin to 1.3.0-SNAPSHOT

Upgrades plugin to 1.3.0-SNAPSHOT

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>
Bumps to pull 1.2.1 dependencies.

Bump to version 1.2.1

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Backports 1.3.0 version bump to 1.x branch.

Backports 1.3 version bump to 1.x

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Coming from https://github.com/opensearch-project/opensearch-build/issues/1417.

Incremented version to 1.2.4.

---

build.gradle

Signed-off-by: Surya Sashank Nistala <snistala@amazon.com>
Removed explicit junit dependency
#90 

Removed explicit junit dependency

---

release-notes/opensearch-asynchronous-search.release-notes-1.3.0.0.md

[Describe what this change achieves]

Adding 1.3.0 release notes - (1.3 branch)

---

release-notes/opensearch-asynchronous-search.release-notes-1.3.0.0.md

[Describe what this change achieves]

Adding 1.3.0 release notes

---

.github/workflows/backport.yml
.github/workflows/delete_backport_branch.yml
DEVELOPER_GUIDE.md

Added auto backport and delete workflows
https://github.com/opensearch-project/asynchronous-search/issues/71

Added auto backport and delete workflows

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Remove hardcoding of versions in workflow
#103

Remove hardcoding of versions in workflow

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Signed-off-by: Sayali Rohidas Gaikawad <gaiksaya@amazon.com>
Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.

Incremented version to 1.3.2.

---

.github/workflows/build.yml

Commenting docker pull step for successful CIs

Commenting docker pull step for successful CIs

---

.github/workflows/build.yml

Reverting the commented lines since CIs are green and docker is available

Revert "Commenting docker pull step for successful CIs"

---

release-notes/opensearch-asynchronous-search.release-notes-2.0.0.0-rc1.md

Adding release notes for 2.0.0-rc1
(https://github.com/opensearch-project/asynchronous-search/issues/96)

Adding release notes for 2.0.0-rc1

---

release-notes/opensearch-asynchronous-search.release-notes-2.0.0.0.md

Adding release dates for 2.0
https://github.com/opensearch-project/asynchronous-search/issues/142

Adding release notes for 2.0

---

release-notes/opensearch-asynchronous-search.release-notes-2.0.0.0.md

[main] Adding release notes for 2.0

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Signed-off-by: pgodithi <pgodithi@amazon.com>
https://github.com/opensearch-project/opensearch-build/issues/2101
https://github.com/opensearch-project/opensearch-build/issues/2101

Version Increment to 1.3.3 OpenSearch release

---

release-notes/opensearch-asynchronous-search.release-notes-2.1.0.0.md

Adds release notes for 2.1
#152 

Adds release notes for 2.1

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Increment to 1.3.4
Part of https://github.com/opensearch-project/opensearch-build/issues/2205

Incremented version to 1.3.4.

---

build.gradle

Bump version to 2.2.0

---

release-notes/opensearch-asynchronous-search.release-notes-2.2.0.0.md

Adding 2.2 release notes

---

src/main/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementService.java
src/test/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementServiceTests.java
src/test/java/org/opensearch/search/asynchronous/utils/TestUtils.java

Signed-off-by: Dhrubajyoti Das <dhruvdas@amazon.com>
Changed 'master' nomenclature to 'cluster_manager'
https://github.com/opensearch-project/asynchronous-search/issues/99

Changed master nomenclature to cluster_manager(2)

---

release-notes/opensearch-asynchronous-search.release-notes-2.3.0.0.md

Adding release notes for 2.3.0
https://github.com/opensearch-project/asynchronous-search/issues/173

adding release notes for 2.3.0

---

release-notes/opensearch-asynchronous-search.release-notes-2.5.0.0.md

Release notes for 2.5
https://github.com/opensearch-project/asynchronous-search/issues/217

Release notes for 2.5

---

release-notes/opensearch-asynchronous-search.release-notes-2.5.0.0.md

[backport 2.5] Release notes for 2.5

---

build.gradle
release-notes/opensearch-asynchronous-search.release-notes-2.6.0.0.md

[backport] release note and bug fix from main to 2.x

---

release-notes/opensearch-asynchronous-search.release-notes-2.6.0.0.md

Add 2.6 release notes

---

release-notes/opensearch-asynchronous-search.release-notes-2.6.0.0.md

[Backport] Update release notes for 2.6

---

src/test/java/org/opensearch/search/asynchronous/integTests/DeleteAsynchronousSearchSingleNodeIT.java
src/test/java/org/opensearch/search/asynchronous/integTests/GetAsynchronousSearchSingleNodeIT.java
src/test/java/org/opensearch/search/asynchronous/integTests/SubmitAsynchronousSearchSingleNodeIT.java

2.6 build failure fix

---

src/test/java/org/opensearch/search/asynchronous/restIT/AsynchronousSearchRestIT.java

Fix 2.6 flaky tests

---

src/test/java/org/opensearch/search/asynchronous/integTests/DeleteAsynchronousSearchSingleNodeIT.java
src/test/java/org/opensearch/search/asynchronous/integTests/GetAsynchronousSearchSingleNodeIT.java
src/test/java/org/opensearch/search/asynchronous/integTests/SubmitAsynchronousSearchSingleNodeIT.java
src/test/java/org/opensearch/search/asynchronous/restIT/ApiParamsValidationIT.java
src/test/java/org/opensearch/search/asynchronous/restIT/AsynchronousSearchRestIT.java

[backport] Fix flaky test in 2.x

---

src/test/java/org/opensearch/search/asynchronous/restIT/ApiParamsValidationIT.java
src/test/java/org/opensearch/search/asynchronous/restIT/AsynchronousSearchRestIT.java

[backport]Fix flaky test in 1.3

---

build.gradle
src/main/java/org/opensearch/search/asynchronous/response/AsynchronousSearchResponse.java
src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchTaskCancellationIT.java
src/test/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementServiceIT.java

Increment version to 2.7

---

src/main/java/org/opensearch/search/asynchronous/plugin/AsynchronousSearchPlugin.java
src/main/java/org/opensearch/search/asynchronous/response/AcknowledgedResponse.java
src/main/java/org/opensearch/search/asynchronous/response/AsynchronousSearchResponse.java
src/main/java/org/opensearch/search/asynchronous/response/AsynchronousSearchStatsResponse.java
src/main/java/org/opensearch/search/asynchronous/service/AsynchronousSearchPersistenceService.java
src/main/java/org/opensearch/search/asynchronous/stats/AsynchronousSearchCountStats.java
src/main/java/org/opensearch/search/asynchronous/stats/AsynchronousSearchStats.java
src/test/java/org/opensearch/search/asynchronous/SecurityEnabledRestTestCase.java
src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchQueryIT.java
src/test/java/org/opensearch/search/asynchronous/response/AsynchronousSearchResponseTests.java
src/test/java/org/opensearch/search/asynchronous/restIT/AsynchronousSearchRestTestCase.java
src/test/java/org/opensearch/search/asynchronous/service/AsynchronousSearchServiceUpdateContextTests.java
src/test/java/org/opensearch/search/asynchronous/utils/RestTestUtils.java

2.x build fixes

---

.github/workflows/maven-publish.yml
build.gradle

Publish snapshot to maven

---

release-notes/opensearch-asynchronous-search.release-notes-2.7.0.0.md

Add 2.7 release notes

---

release-notes/opensearch-asynchronous-search.release-notes-2.7.0.0.md

[backport 2.7] Release notes for 2.7

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

 Increment version to 2.8

---

.github/CODEOWNERS
MAINTAINERS.md
release-notes/opensearch-asynchronous-search.release-notes-2.8.0.0.md

Updating maintainers file (#275)

---

build.gradle
src/main/java/org/opensearch/search/asynchronous/transport/TransportSubmitAsynchronousSearchAction.java
src/test/java/org/opensearch/search/asynchronous/integTests/AsynchronousSearchRejectionIT.java
src/test/java/org/opensearch/search/asynchronous/listener/AsynchronousSearchCancellationIT.java
src/test/java/org/opensearch/search/asynchronous/listener/AsynchronousSearchPartialResponseIT.java
src/test/java/org/opensearch/search/asynchronous/listener/AsynchronousSearchProgressListenerIT.java
src/test/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementServiceTests.java

Increment version to 2.9.0

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Increment version to 1.3.12-SNAPSHOT

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Incrementing guava version and increasing heap size

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Adding release workflow

---

.github/workflows/auto-release.yml
build.gradle

Backport auto release workflow to 2.x

---

.github/workflows/auto-release.yml

Fix release notes name

---

release-notes/opensearch-asynchronous-search.release-notes-2.9.0.0.md

Add release notes for 2.9.0

---

release-notes/opensearch-asynchronous-search.release-notes-2.10.0.0.md

Add release notes for 2.10.0

---

release-notes/opensearch-asynchronous-search.release-notes-2.10.0.0.md

Signed-off-by: Arpit Bandejiya <abandeji@amazon.com>
(cherry picked from commit 0a5e90249d73684d57a4b64168371df37d218c16)

[Backport] Add 2.10.0 release notes

---

release-notes/opensearch-asynchronous-search.release-notes-2.11.0.0.md

Backport https://github.com/opensearch-project/asynchronous-search/pull/446

[Backport] Add 2.11 release notes

---

release-notes/opensearch-asynchronous-search.release-notes-2.12.0.0.md

Adding release notes for 2.12.0

Adding release notes for 2.12.0

---

release-notes/opensearch-asynchronous-search.release-notes-2.13.0.0.md

Release notes for 2.13

---

.github/workflows/backport.yml

Bumps VachaShah/backport and tibdex/github-app-token to latest versions.
N/A

Update backport workflow to latest versions

---

.github/CODEOWNERS

Fixing errors in the CODEOWNERS files 

Fix andrross and RS146BIJAY aliases

---

release-notes/opensearch-asynchronous-search.release-notes-2.14.0.0.md

Add release notes for 2.14.0
N/A

Add release notes for 2.14.0

---

.github/workflows/build.yml
.github/workflows/multi-node-test-workflow.yml
build.gradle

Increment version to 1.3.17-SNAPSHOT

---

release-notes/opensearch-asynchronous-search.release-notes-2.15.0.0.md

Description
Add release notes for 2.15.0
Issues Resolved
N/A

Add release notes for 2.15.0

---

release-notes/opensearch-asynchronous-search.release-notes-2.16.0.0.md

Add release notes for 2.16.0
N/A

Add release notes for 2.16.0

---

release-notes/opensearch-asynchronous-search.release-notes-2.17.0.0.md

Add 2.17 release notes

---

release-notes/opensearch-asynchronous-search.release-notes-2.17.0.0.md

Backport 2.17 release notes
N/A

2.17 release notes

---

build.gradle

bump bwc version on main to 2.18.0.0

bump bwc version on main to 2.18.0.0

---

gradle/wrapper/gradle-wrapper.properties

Update gradle to 8.10.1

---

release-notes/opensearch-asynchronous-search.release-notes-2.18.0.0.md

2.18 release notes

---

release-notes/opensearch-asynchronous-search.release-notes-2.16.0.0.md
release-notes/opensearch-asynchronous-search.release-notes-2.17.0.0.md
release-notes/opensearch-asynchronous-search.release-notes-2.18.0.0.md

Add 2.16, 2.17, 2.18 release notes to 2.x.
N/A

2.16, 2.17, 2.18 release notes

---

release-notes/opensearch-asynchronous-search.release-notes-2.19.0.0.md

[2.19] Release notes

---

release-notes/opensearch-asynchronous-search.release-notes-2.19.1.0.md

Release notes 2.19.1

---

release-notes/opensearch-asynchronous-search.release-notes-3.0.0.0-alpha1.md

Add 3.0.0.0-alpha1 releasenotes
https://github.com/opensearch-project/opensearch-build/issues/3747
https://github.com/opensearch-project/asynchronous-search/issues/318
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please check …

Add 3.0.0.0-alpha1 releasenotes

---

release-notes/opensearch-asynchronous-search.release-notes-3.0.0.0-beta1.md

Add release notes for 3.0.0.0-beta1.
No new changes.
#318
~~- [ ] New functionality includes testing.~~
~~- [ ] New functionality has been documented.~~
~~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
~~- [ ] Commits are signed per the DCO using `--signoff`.~~
~~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/asynchronous-search/blob/main/CONTR …

Add release notes for 3.0.0.0-beta1.

---

release-notes/opensearch-asynchronous-search.release-notes-3.1.0.0.md

3.1 release notes
N/A
~~- [ ] New functionality includes testing.~~
~~- [ ] New functionality has been documented.~~
~~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
~~- [ ] Commits are signed per the DCO using `--signoff`.~~
~~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/asynchronous-search/blob/main/CONTRIBUTING.md#developer-certificate-of- …

3.1 release notes
